# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"
  An introduction to some of the mathematical and statistical 
  methods used in the analysis of social and natural scientific 
  phenomena with an emphasis on the interpretation of 
  experimental and survey data. Topics include elementary and 
  combinatorial designs, basic statistical methods, correlation 
  and inference, and regression analysis. Applications to the 
  students’ major disciplines are included throughout the course 
  as well as in one or more substantial projects.
baseurl: "/math215" # the subpath of your site, e.g. /blog
url: "https://hendrix-cs.github.io" # the base hostname & protocol for your site, e.g. http://example.com

number: MATH 215
title: Introductory Statistics
semester: Fall 2023
hypothesis: false

jumbotext: slidebackground.com
jumbourl: https://www.slidebackground.com/free-image/quality-school-statistics-free-backgrounds-1835.html

navigation:
  - title: Overview
    subfolderitems:
      - page: Description
        url: '#description'
      - page: Learning Goals
        url: '#goals'
      - page: Resources
        url: '#resources'
  - page: Code
    url: '#inclasscode'
  - page: Calendar
    url: 'https://app.teamgantt.com/public/projects/calendar/?ids=3632637&projectIds=3632637&publicKeys=xejRn6hKircu&prefs=P2lkcz0zNjMyNjM3JnB1YmxpY19rZXlzPXhlalJuNmhLaXJjdQ%3D%3D'
  - title: Coursework
    subfolderitems:
      - page: Checkpoints
        url: '#hwqz'
      - page: Labs
        url: '#labs'
      - page: Project
        url: '#projects'
      - page: Exams
        url: '#exams'
      - page: Grading
        url: '#scale'
  - page: Commitments
    url: '#commitments'

instructors:
  - id: yorgey
    name: Dr. Brent Yorgey
    email: yorgey@hendrix.edu
    web: http://ozark.hendrix.edu/~yorgey
    phone: (501) 450-1377
    officehours: https://byorgey.youcanbook.me
  - id: goadrich
    name: Dr. Mark Goadrich
    email: goadrich@hendrix.edu
    web: http://mark.goadrich.com
    phone: (501) 450-1367
    officehours: http://markgoadrich.youcanbook.me/
  - id: ferrer
    name: Dr. Gabriel Ferrer
    email: ferrer@hendrix.edu
    web: http://ozark.hendrix.edu/~ferrer
    phone: (501) 450-3879
    officehours: https://drferrer.youcanbook.me/
  - id: seme
    name: Prof. Lars Seme
    email: seme@hendrix.edu
    web: https://www.hendrix.edu/mathcs/profile.aspx?id=70795
    phone: (501) 450-1256
    officehours: ???

offerings:
  - name: LECTURE 01
    loc: MCREY 110
    time: TR 9:45am - 11:00am
    instructor: goadrich

resources:
  - name: Statistical Reasoning Textbook
    image: assets/images/oli.jpeg
    url: https://oli.cmu.edu/courses/statistical-reasoning/
  - name: Kaggle
    image: assets/images/kaggle_icon.png
    url: https://www.kaggle.com/
  - name: Tidyverse
    image: assets/images/tidyverse.png
    url: https://www.tidyverse.org/


extra-resources:
  - name: Introduction to Modern Statistics
    image: assets/images/openintro_logo.webp
    url: https://openintro-ims.netlify.app/
  - name: OpenStax Introductory Statistics
    image: assets/images/osxlogo.png
    url: https://openstax.org/details/books/introductory-statistics
  - name: Learning Statistics with R
    image: assets/images/djnavarro.jpeg
    url: https://learningstatisticswithr.com/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
